// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 vertexclique
// Licensed under the Business Source License 1.1.
// Change Date: 10 years after this version's release. Change License: Apache-2.0.

//! Effect-wrapped `wasi_snapshot_preview1` imports for the WASI-command
//! substrate (Ruby / Rust / Go / C / C++).
//!
//! Unlike the JS engine (host functions) and the Emscripten/Pyodide path
//! (custom preview1 shims over [`InMemFs`](crate::emscripten_fs::InMemFs)),
//! these languages reach the host through **stock** `wasmtime-wasi` preview1
//! only: they intercept nothing today. This module adds the one net-new seam
//! that is feasible against `wasmtime-wasi` 44 without forking it: it re-wires
//! the `clock_time_get` and `random_get` imports over the stock ones (with
//! [`allow_shadowing`](wasmtime::Linker::allow_shadowing)) and routes each
//! through the shared record/replay [`seam`](crate::effect_seam::seam) - the
//! same one the JS substrate uses, so the record/replay parity logic is
//! single-sourced.
//!
//! # Why only clock + random (the honest ceiling)
//!
//! The design wants every effect-bearing preview1 import wrapped (`path_open`,
//! `fd_read`, `fd_write`, ...) with the wrapper *delegating* to the stock
//! method on a record run. That delegation is **not achievable** with
//! `wasmtime-wasi` 44's public API:
//!
//! * the stock preview1 impl is the private `wasi_snapshot_preview1::
//!   WasiSnapshotPreview1` trait generated by `wiggle::from_witx!` inside the
//!   `p1` module ("None of the generated modules, traits, or types should be
//!   used externally to this module"), and its filesystem methods are `async`;
//! * the wiggle wrappers resolve guest memory via `caller.get_export("memory")`
//!   using the **calling instance**, so re-invoking a captured stock `Func`
//!   from inside a host wrapper bails with "missing required memory export"
//!   (the synthetic caller has no instance).
//!
//! So a wrapped `fd_read` / `fd_write` could observe the request but could not
//! perform the real read/write, and reimplementing the file operations against
//! the host FS would mean owning the whole fd table (a second WASI
//! implementation) - out of scope, and contradicting the "reuse stock
//! wasmtime-wasi" intent. `clock_time_get` and `random_get`, by contrast, are
//! self-contained (no fd table, no delegation): the wrapper fully owns the
//! effect, so they are captured here honestly and completely.
//!
//! Filesystem effects in this substrate are surfaced at the host preopen
//! boundary instead (the `/.afb` return-frame and the session root); env stays
//! host-provisioned through
//! [`WasiCommandOpts`](crate::embedder_vm::WasiCommandOpts). Sockets and child
//! processes do not exist in this WASI build, so `Net` and `Process` effects
//! are genuinely N/A for the command languages (only `Fs`, `Env`, `Clock`,
//! `Random` are real).
//!
//! # Determinism
//!
//! On a record run (or with no recording host) the produced clock and random
//! bytes are deterministic (a fixed virtual epoch and a fixed-seed fill),
//! matching the sealed, reproducible posture of
//! [`deterministic_engine`](crate::embedder_vm::deterministic_engine) and the
//! Emscripten clock shim (both use [`VIRTUAL_EPOCH_NS`]). Re-running the same
//! source yields byte-identical clock/random reads, so record and replay agree.

use afterburner_core::{EffectDetail, EffectKind, HostEffect, Result};
use wasmtime::{Caller, Extern};

use crate::effect_seam::{self, Seamed};
use crate::embedder_vm::{EmbedderLinker, EmbedderState};
use crate::emscripten_abi::VIRTUAL_EPOCH_NS;

// ---- WASI errno constants (wasi_snapshot_preview1 values, positive) ---------

/// WASI errno: success.
const ERRNO_SUCCESS: i32 = 0;
/// WASI errno: bad address (a guest pointer that does not map into memory).
const ERRNO_FAULT: i32 = 21;
/// WASI errno: invalid argument (e.g. a recorded payload too short to satisfy
/// the request).
const ERRNO_INVAL: i32 = 28;

// ---- guest-memory write helper ----------------------------------------------

/// Write `bytes` into the guest's exported linear memory at `ptr`
/// (u32 address space). Returns `false` when the module exports no `memory`
/// or the range is out of bounds.
///
/// WASI command modules **export** their memory as `"memory"` (unlike the
/// Emscripten modules that import it as `env.memory`), so this resolves it via
/// [`Caller::get_export`] rather than [`EmbedderState`]'s stored handle.
fn write_bytes(caller: &mut Caller<'_, EmbedderState>, ptr: i32, bytes: &[u8]) -> bool {
    let mem = match caller.get_export("memory") {
        Some(Extern::Memory(m)) => m,
        _ => return false,
    };
    let data = mem.data_mut(&mut *caller);
    let start = ptr as u32 as usize;
    let end = match start.checked_add(bytes.len()) {
        Some(e) => e,
        None => return false,
    };
    if end > data.len() {
        return false;
    }
    data[start..end].copy_from_slice(bytes);
    true
}

// ---- deterministic value sources --------------------------------------------

/// The deterministic clock value for a WASI clock id. All ids return the fixed
/// virtual epoch (nanoseconds), identical to the Emscripten clock shim so the
/// two substrates cannot disagree on "the sealed clock". Elapsed time between
/// two reads is therefore zero: correct for a sealed, reproducible run.
fn deterministic_clock(_clock_id: i32) -> u64 {
    VIRTUAL_EPOCH_NS
}

/// Fill `n` bytes with a deterministic, fixed-seed stream (a SplitMix64
/// expansion). No per-run or process-global state, so identical runs produce
/// identical bytes (the record/replay parity property); this is sealed-run
/// entropy, not cryptographic randomness.
fn deterministic_random(n: usize) -> Vec<u8> {
    const SEED: u64 = 0x9E37_79B9_7F4A_7C15;
    let mut out = Vec::with_capacity(n);
    let mut s = SEED;
    while out.len() < n {
        s = s.wrapping_add(SEED);
        let mut z = s;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^= z >> 31;
        let take = (n - out.len()).min(8);
        out.extend_from_slice(&z.to_le_bytes()[..take]);
    }
    out
}

// ---- effect target strings ---------------------------------------------------
//
// `afterburner-core` ships canonical target builders for Fs/Process/Net/Env/Db
// but not Clock/Random (no cross-substrate spelling risk today: only this
// substrate emits them). They are spelled here, once, so the two are still
// single-sourced within the crate.

/// `"clock::"` + the clock kind for a WASI clock id.
fn clock_target(clock_id: i32) -> String {
    let kind = match clock_id {
        0 => "realtime",
        1 => "monotonic",
        2 => "process_cputime",
        3 => "thread_cputime",
        _ => "unknown",
    };
    format!("clock::{kind}")
}

/// `"random::getrandom"` - the canonical random-source identity.
fn random_target() -> String {
    "random::getrandom".to_string()
}

// ---- linker wiring -----------------------------------------------------------

/// Re-wire the effect-bearing, self-contained preview1 imports over the stock
/// `wasmtime-wasi` ones.
///
/// Call this from the `setup` callback of
/// [`EmbedderVm::compile`](crate::embedder_vm::EmbedderVm::compile) for a WASI
/// command module compiled with `wasi: true`, i.e. **after**
/// `add_to_linker_sync` has wired the stock imports (the setup callback runs
/// after WASI wiring). It enables
/// [`allow_shadowing`](wasmtime::Linker::allow_shadowing) and redefines
/// `clock_time_get` and `random_get`.
///
/// The wrappers read the per-run recording host from
/// [`EmbedderState::host_context`] at call time (set by
/// [`run_command_with_host`](crate::embedder_vm::EmbedderVm::run_command_with_host)),
/// so one compiled module serves both a sealed run (no host) and a recording /
/// replaying run (a host) without recompilation.
///
/// See the module docs for why the filesystem and env imports are intentionally
/// left on the stock impl.
pub fn wire_effect_wrapped_wasi(linker: &mut EmbedderLinker<'_>) -> Result<()> {
    // Redefining an already-defined import requires shadowing to be enabled.
    linker.inner_mut().allow_shadowing(true);

    // clock_time_get(id: clockid, precision: timestamp, time_out: *timestamp) -> errno
    linker.func_wrap(
        "wasi_snapshot_preview1",
        "clock_time_get",
        |mut caller: Caller<'_, EmbedderState>,
         clock_id: i32,
         _precision: i64,
         time_out: i32|
         -> i32 {
            let host = caller.data().host_context.clone();
            let effect = HostEffect::new(
                EffectKind::Clock,
                clock_target(clock_id),
                Vec::new(),
                EffectDetail::None,
                None,
            );
            // The "real effect" is producing the sealed deterministic value;
            // the shared seam records it (record run) or substitutes a recorded
            // one (replay). Clock reads never fail, so `real` is infallible.
            let seamed = effect_seam::seam(host, effect, move |_e| {
                Ok((
                    deterministic_clock(clock_id).to_le_bytes().to_vec(),
                    effect_seam::ok(),
                ))
            });
            match seamed {
                Seamed::Output { bytes, .. } => {
                    if bytes.len() < 8 {
                        return ERRNO_INVAL;
                    }
                    if write_bytes(&mut caller, time_out, &bytes[..8]) {
                        ERRNO_SUCCESS
                    } else {
                        ERRNO_FAULT
                    }
                }
                // A recorded/replayed clock error is not a real WASI condition;
                // surface EINVAL rather than fabricate a timestamp.
                Seamed::ReplayedError(_) | Seamed::LiveError(_) => ERRNO_INVAL,
            }
        },
    )?;

    // random_get(buf: *u8, buf_len: size) -> errno
    linker.func_wrap(
        "wasi_snapshot_preview1",
        "random_get",
        |mut caller: Caller<'_, EmbedderState>, buf: i32, buf_len: i32| -> i32 {
            let host = caller.data().host_context.clone();
            let n = buf_len as u32 as usize;
            let effect = HostEffect::new(
                EffectKind::Random,
                random_target(),
                Vec::new(),
                EffectDetail::None,
                None,
            );
            let seamed = effect_seam::seam(host, effect, move |_e| {
                Ok((deterministic_random(n), effect_seam::ok()))
            });
            match seamed {
                Seamed::Output { bytes, .. } => {
                    if bytes.len() < n {
                        return ERRNO_INVAL;
                    }
                    if write_bytes(&mut caller, buf, &bytes[..n]) {
                        ERRNO_SUCCESS
                    } else {
                        ERRNO_FAULT
                    }
                }
                Seamed::ReplayedError(_) | Seamed::LiveError(_) => ERRNO_INVAL,
            }
        },
    )?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn deterministic_random_is_reproducible_and_sized() {
        for n in [0usize, 1, 7, 8, 9, 31, 64, 200] {
            let a = deterministic_random(n);
            let b = deterministic_random(n);
            assert_eq!(a.len(), n, "produces exactly n bytes");
            assert_eq!(a, b, "same length -> identical bytes (sealed determinism)");
        }
    }

    #[test]
    fn deterministic_random_is_not_all_zero() {
        // A trivially-broken fill (all zeros) would still be "deterministic";
        // guard that the stream actually varies.
        let bytes = deterministic_random(64);
        assert!(bytes.iter().any(|&b| b != 0), "fill must not be all zero");
        assert!(
            bytes.windows(8).any(|w| w[0] != w[4]),
            "fill must vary within the stream"
        );
    }

    #[test]
    fn deterministic_clock_is_virtual_epoch() {
        for id in 0..4 {
            assert_eq!(deterministic_clock(id), VIRTUAL_EPOCH_NS);
        }
    }

    #[test]
    fn clock_target_forms_are_fixed() {
        assert_eq!(clock_target(0), "clock::realtime");
        assert_eq!(clock_target(1), "clock::monotonic");
        assert_eq!(clock_target(2), "clock::process_cputime");
        assert_eq!(clock_target(3), "clock::thread_cputime");
        assert_eq!(clock_target(99), "clock::unknown");
        assert_eq!(random_target(), "random::getrandom");
    }
}
